# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = VolumeViz
DESTDIR = ../x64/Release
CONFIG += release console
LIBS += -L"." \
    -lOpenGL32 \
    -lcl/OpenCL
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += .
include(VolumeViz.pri)
win32:RC_FILE = VolumeViz.rc
